# Generated by Django 4.2 on 2023-05-04 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0008_recommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("remain", models.IntegerField(default=-1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.restaurant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=20)),
                (
                    "pg_transaction_number",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("CARD", "카드")], default="CARD", max_length=4
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "결제대기"),
                            ("PAID", "결제완료"),
                            ("FAILED", "예약실패"),
                            ("CANCELED", "예약취소"),
                        ],
                        default="READY",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(default=None, null=True)),
                ("canceled_at", models.DateTimeField(default=None, null=True)),
                (
                    "booker_name",
                    models.CharField(default=None, max_length=20, null=True),
                ),
                (
                    "booker_phone",
                    models.CharField(default=None, max_length=20, null=True),
                ),
                (
                    "booker_comment",
                    models.CharField(default=None, max_length=200, null=True),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.restaurant"
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.availableseat",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="restauranttable",
            name="weekday",
            field=models.CharField(
                choices=[
                    ("MON", "월요일"),
                    ("TUE", "화요일"),
                    ("WEB", "수요일"),
                    ("THU", "목요일"),
                    ("FRI", "금요일"),
                    ("SAT", "토요일"),
                    ("SUN", "일요일"),
                ],
                default="MON",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="PayHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.booking"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.restauranttable"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="availableseat",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.restauranttable"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="availableseat",
            unique_together={("restaurant", "table", "datetime")},
        ),
    ]
