# Generated by Django 4.2 on 2023-05-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_userverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userverification",
            name="key",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
