# Generated by Django 4.2 on 2023-05-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_userverification_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userverification",
            name="verified_at",
            field=models.DateTimeField(null=True),
        ),
    ]
