# Generated by Django 4.2 on 2023-05-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_availableseat_booking_alter_restauranttable_weekday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(max_length=30),
        ),
    ]
