# Generated by Django 4.2 on 2023-05-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_alter_restaurant_address_alter_restaurant_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="main_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                to="web.restaurantimage",
                verbose_name="메인 이미지",
            ),
        ),
    ]
